# Generated by Django 4.2.1 on 2023-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appdataextractor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('expediente', models.CharField(max_length=20)),
                ('unidad_fiscalizable', models.CharField(max_length=200)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=100)),
            ],
        ),
    ]
